---
abstract: 'merge .pod files into their .pm counterparts'
author:
  - 'Yanick Champoux <yanick@babyl.dyndns.org>'
build_requires:
  Carp: 0
  Module::Build: 0.3601
  Scalar::Util: 0
  Test::More: 0.94
  perl: 5.004
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300002, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-CoalescePod
provides:
  Dist::Zilla::Plugin::CoalescePod:
    file: lib/Dist/Zilla/Plugin/CoalescePod.pm
    version: v0.1.0
requires:
  Dist::Zilla::Role::FileMunger: 0
  Moose: 0
  strict: 0
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-CoalescePod
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-CoalescePod/
version: 0.1.0
x_authority: cpan:YANICK
